import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
  InjectPerfectDarkMode,
  usePerfectDarkMode,
} from 'next-plugin-perfect-dark-mode'

const Home: NextPage = () => {
  const { modeSaved: mode, setMode } = usePerfectDarkMode()
  const onClickedMode = () => {
    const newMode = (() => {
      if (mode === undefined) return 'dark'
      if (mode === 'dark') return 'light'
      if (mode === 'light') return undefined
    })()
    setMode(newMode)
  }
  return (
    <div className={styles.container}>
      <InjectPerfectDarkMode />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={onClickedMode}>{mode || 'system'}</button>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  )
}

export default Home
